//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartePartie
    {
        public int Id { get; set; }
        public int PartieId { get; set; }
    
        public virtual Partie Partie { get; set; }
        public virtual Carte Carte { get; set; }
    }
}
