//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Joueur> JoueurSet { get; set; }
        public virtual DbSet<Partie> PartieSet { get; set; }
        public virtual DbSet<JoueurPartie> JoueurPartieSet { get; set; }
        public virtual DbSet<De> DeSet { get; set; }
        public virtual DbSet<Carte> CarteSet { get; set; }
    }
}
